# Generated by Django 3.2.4 on 2021-07-19 11:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWSafe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='Active sur le dossier')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date création')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('lettremission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.lettremission', verbose_name='Mission')),
                ('rolecollaborateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.scope', verbose_name='En charge de')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile', verbose_name='Collaborateur')),
            ],
            options={
                'unique_together': {('username', 'lettremission')},
            },
        ),
    ]
