# Generated by Django 3.2.4 on 2021-07-20 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0001_initial'),
        ('accounts', '0002_pwsafe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwsafe',
            name='rolecollaborateur',
        ),
        migrations.AddField(
            model_name='pwsafe',
            name='responsable',
            field=models.BooleanField(default=True, verbose_name='Responsable du dossier'),
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='Active sur le dossier')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date création')),
                ('lettremission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.lettremission', verbose_name='Mission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Collaborateur')),
            ],
            options={
                'unique_together': {('user', 'lettremission')},
            },
        ),
    ]
