# Generated by Django 3.2.4 on 2021-09-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(upload_to='files/csvs', verbose_name='Nom fichier'),
        ),
    ]
