# Generated by Django 3.2.4 on 2021-07-08 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True, verbose_name='Ville')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Raison Sociale')),
                ('adresse', models.TextField(max_length=300, null=True, verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=50, null=True, verbose_name='Code Postal')),
                ('national_law', models.BooleanField(default=True, verbose_name='De Droit National ?')),
                ('ice', models.CharField(blank=True, max_length=15, null=True, verbose_name='ICE')),
                ('identifiant_fiscal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Identifiant Fiscal')),
                ('cnss', models.CharField(blank=True, max_length=10, null=True, verbose_name='Num Affiliation CNSS')),
                ('rc', models.CharField(blank=True, max_length=10, null=True, verbose_name='Num Registre de Commerce')),
                ('tp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Num Taxe Professionnelle')),
                ('activity', models.TextField(max_length=300, null=True, verbose_name='Activité')),
                ('fiscal_year', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=1, verbose_name="Mois d'Ouverture Année Fiscale")),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Date de Création')),
                ('share_capital', models.FloatField(blank=True, verbose_name='Capital Social')),
                ('nominal_value', models.FloatField(blank=True, verbose_name='Valeur Nominale')),
                ('statut', models.IntegerField(choices=[(0, 'En Attente'), (1, 'Actif'), (2, 'Suspendu'), (3, 'InActif')], default=0, verbose_name='Statut')),
                ('terminate_date', models.DateField(blank=True, null=True, verbose_name='Date de Cessation/Dissolution')),
                ('liquidation_date', models.DateField(blank=True, null=True, verbose_name='Date de Liquidation')),
                ('file', models.ImageField(blank=True, null=True, upload_to='files/customers/logo', verbose_name='Joindre Logo')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.city', verbose_name='Ville')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code_country', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Code Nationalité')),
                ('country', models.CharField(max_length=50, unique=True, verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Code Devise')),
                ('currency', models.CharField(max_length=50, unique=True, verbose_name='Devise et Pays')),
            ],
        ),
        migrations.CreateModel(
            name='LegalForm',
            fields=[
                ('code_lf', models.IntegerField(primary_key=True, serialize=False, verbose_name='Code FJ')),
                ('lf_name', models.CharField(max_length=20, unique=True, verbose_name='Sigle')),
                ('full_lf_name', models.CharField(max_length=300, verbose_name='Forme Juridique')),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('code_nationality', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Code Pays')),
                ('nationality', models.CharField(max_length=50, unique=True, verbose_name='Nationalité')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('code_lf', models.IntegerField(primary_key=True, serialize=False, verbose_name='Code Cabinet')),
                ('office', models.CharField(max_length=100, unique=True, verbose_name='Cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('civility', models.IntegerField(choices=[(1, 'Monsieur'), (2, 'Madame')], verbose_name='Civilité')),
                ('id_card', models.IntegerField(choices=[(1, 'CNIE'), (2, 'Passeport'), (3, 'Carte Séjours')], null=True, verbose_name="Pièce d'Identité")),
                ('id_numbre', models.CharField(max_length=20, null=True, verbose_name="Numéro Pièce d'Identité")),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lieu de naissance')),
                ('adresse', models.CharField(max_length=300, null=True, verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=50, null=True, verbose_name='Code Postal')),
                ('resident', models.BooleanField(default=True, verbose_name='Résident National ?')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.city', verbose_name='Ville')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.country', verbose_name='Pays')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.nationality', verbose_name='Nationalité')),
            ],
            options={
                'unique_together': {('last_name', 'first_name')},
            },
        ),
        migrations.CreateModel(
            name='RoleRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolerepresentative', models.CharField(max_length=200, unique=True, verbose_name='Rôle du Représentant')),
            ],
        ),
        migrations.CreateModel(
            name='ShareholderLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_participation', models.DateTimeField(auto_now=True, verbose_name='Date de participation')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company', verbose_name='Raison Sociale')),
            ],
        ),
        migrations.CreateModel(
            name='RepresentativeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_nomination', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company', verbose_name='Raison Sociale')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(default='212', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.country', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(default='MAD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.currency', verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.legalform', verbose_name='Forme Juridique'),
        ),
        migrations.AddField(
            model_name='company',
            name='nationality',
            field=models.ForeignKey(blank=True, default='212', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.nationality', verbose_name='Nationalité'),
        ),
        # migrations.CreateModel(
        #     name='BankAcount',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('bank_name', models.CharField(max_length=100, verbose_name='Banque')),
        #         ('agency', models.CharField(max_length=100, verbose_name='Agence')),
        #         ('rib', models.CharField(max_length=24, unique=True, verbose_name='RIB')),
        #         ('closed', models.BooleanField(default=False, verbose_name='Compte Clôturé ?')),
        #         ('clos_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
        #         ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company')),
        #     ],
        # ),
        migrations.CreateModel(
            name='ShareholderCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.IntegerField(verbose_name="Nombre d'Action")),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company', verbose_name='Société Actionnaire')),
                ('shareholderlink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.shareholderlink', verbose_name='Raison Sociale')),
            ],
            options={
                'unique_together': {('company', 'shareholderlink')},
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.IntegerField(verbose_name="Nombre d'Action")),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company', verbose_name='Raison Sociale')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.person', verbose_name="Nom de l'Actionnaire")),
            ],
            options={
                'unique_together': {('company', 'person')},
            },
        ),
        migrations.CreateModel(
            name='RepresentativeCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_nomination', models.DateTimeField(auto_now=True, verbose_name='Date de Nomination')),
                ('terminate_role', models.BooleanField(default=False, verbose_name='Fin de Mandat ?')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company', verbose_name='Raison Sociale')),
                ('representativelink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.representativelink', verbose_name='Société Représentée')),
                ('rolerepresentative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.rolerepresentative', verbose_name='Rôle du Représentant')),
            ],
            options={
                'unique_together': {('company', 'representativelink')},
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_nomination', models.DateTimeField(auto_now=True, verbose_name='Date de Nomination')),
                ('terminate_role', models.BooleanField(default=False, verbose_name='Fin de Mandat ?')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company', verbose_name='Raison Sociale')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.person', verbose_name='Nom du Représentant')),
                ('rolerepresentative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.rolerepresentative', verbose_name='Rôle du Représentant')),
            ],
            options={
                'unique_together': {('company', 'person')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fonction', models.CharField(max_length=100, verbose_name='Fonction')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Téléphone')),
                ('active', models.BooleanField(default=1, verbose_name='Actif ?')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company', verbose_name='Raison Sociale')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.person', verbose_name='Nom du Contact')),
            ],
            options={
                'unique_together': {('company', 'person')},
            },
        ),
    ]
