# Generated by Django 3.2.4 on 2021-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ville'),
        ),
    ]
