# Generated by Django 3.2.4 on 2021-08-20 21:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_company_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAcount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banque')),
                ('agency', models.CharField(max_length=100, verbose_name='Agence')),
                ('rib', models.CharField(max_length=24, unique=True, verbose_name='RIB')),
                ('bic', models.CharField(blank=True, max_length=6, verbose_name='Code BIC/SWIFT')),
                ('iban', models.CharField(blank=True, max_length=2, verbose_name='Code IBAN')),
                ('closed', models.BooleanField(default=False, verbose_name='Compte Clôturé ?')),
                ('clos_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company')),
            ],
            options={
                'unique_together': {('company', 'bank_name')},
            },
        ),
    ]
