# Generated by Django 3.2.4 on 2021-08-21 19:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_bankacount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankacount',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/customers/rib', verbose_name='Joindre RIB'),
        ),
        migrations.AddField(
            model_name='company',
            name='file_if',
            field=models.FileField(blank=True, null=True, upload_to='files/customers/if', verbose_name='Joindre Bulletin IF'),
        ),
        migrations.AddField(
            model_name='company',
            name='file_rc',
            field=models.FileField(blank=True, null=True, upload_to='files/customers/rc', verbose_name='Joindre Extrat RC'),
        ),
        migrations.AddField(
            model_name='person',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/customers/id_card', verbose_name='Joindre ID Card'),
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('date_contact', models.DateField(auto_created=True, verbose_name='Date Prise Contact')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.IntegerField(choices=[(0, 'Prise de Contact'), (1, 'Rappel'), (2, 'Proposition/LDM'), (3, 'Client'), (4, 'Abandon')], default=0, verbose_name='Statut')),
                ('comment', models.TextField(null=True, verbose_name='Commentaire')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.contact', verbose_name='Contact')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.office', verbose_name='Cabinet')),
            ],
            options={
                'unique_together': {('contact', 'office')},
            },
        ),
    ]
