# Generated by Django 3.2.4 on 2021-08-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210821_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.ForeignKey(default='212', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(default='212', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.nationality', verbose_name='Nationalité'),
        ),
    ]
