# Generated by Django 3.2.4 on 2021-08-23 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20210822_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company'),
        ),
    ]
