# Generated by Django 3.2.4 on 2021-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_contact_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='ip',
            field=models.CharField(blank=True, max_length=100, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='office',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pass'),
        ),
        migrations.AddField(
            model_name='office',
            name='port',
            field=models.CharField(blank=True, max_length=100, verbose_name='Port'),
        ),
    ]
